# Generated by Django 3.2.15 on 2022-10-22 09:22

import colorfield.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None, validators=[django.core.validators.RegexValidator(regex='^#[\\w]{1,8}$')], verbose_name='Цветовой код'),
        ),
    ]
