# Generated by Django 3.2.15 on 2022-11-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followauthor',
            options={'verbose_name': 'Подписки на авторов', 'verbose_name_plural': 'Подписки на авторов'},
        ),
    ]
